import { mt, type ManualBlock, type ManualSection } from "./auditManualTypes";

const same = (v: string) => mt(v, v);

export const AUDIT_MANUAL_DEMO_SECTIONS: ManualSection[] = [
  {
    id: "demo-data",
    number: "A",
    area: "demo",
    sourceOrder: "Illustrative data",
    title: mt("Illustrative / Demo Data in the source", "Source-এর Illustrative / Demo Data"),
    description: mt(
      "These values are explicitly labelled illustrative in the source and are not actual NBR data. They are retained here because they are part of the framework document.",
      "Source এগুলোকে স্পষ্টভাবে illustrative বলে; এগুলো actual NBR data নয়। Framework document-এর অংশ বলে এখানে সংরক্ষিত।"
    ),
    keywords: ["demo","illustrative","population","management dashboard","demo-1","demo-2","demo-3","presets"],
    blocks: [
      {
        kind: "callout",
        tone: "warning",
        text: mt("All figures in this section are sample/demo values used to demonstrate structure and behavior. They must not be interpreted as real taxpayer or NBR population statistics.","এই section-এর সব figure sample/demo, structure ও behavior দেখানোর জন্য। এগুলো real taxpayer বা NBR population statistic নয়।"),
      },
      {
        kind: "table",
        title: mt("Management population dashboard — illustrative aggregates","Management population dashboard — illustrative aggregate"),
        columns: [mt("Chart","Chart"), mt("Category","Category"), mt("Demo value","Demo value")],
        rows: [
          [same("Cases by Risk Level"),same("Low"),same("1,840")],
          [same("Cases by Risk Level"),same("Medium"),same("420")],
          [same("Cases by Risk Level"),same("High"),same("96")],
          [same("Cases by Risk Level"),same("Very High"),same("18")],
          [same("Cases by Risk Level"),mt("Undetermined","নির্ণয় হয়নি"),same("310")],
          [same("Coverage distribution"),same("DT0"),same("960")],
          [same("Coverage distribution"),same("DT1"),same("640")],
          [same("Coverage distribution"),same("DT1+H"),same("720")],
          [same("Coverage distribution"),same("DT2"),same("310")],
          [same("Coverage distribution"),same("DT3"),same("54")],
          [same("Signals by frequency"),same("R-C1"),same("240")],
          [same("Signals by frequency"),same("R-A1"),same("180")],
          [same("Signals by frequency"),same("R-B1"),same("150")],
          [same("Signals by frequency"),same("R-C4"),same("70")],
          [same("Signals by frequency"),same("R-A2"),same("64")],
          [same("Signals by frequency"),same("R-E2"),same("12")],
          [same("Control flags by frequency"),same("F0"),same("310")],
          [same("Control flags by frequency"),same("F1"),same("190")],
          [same("Control flags by frequency"),same("F5"),same("120")],
          [same("Control flags by frequency"),same("F2"),same("45")],
          [same("Reconciliation gap distribution"),same("< materiality"),same("1,520")],
          [same("Reconciliation gap distribution"),same("1–3× materiality"),same("280")],
          [same("Reconciliation gap distribution"),same("> 3× materiality"),same("114")],
          [same("Reconciliation gap distribution"),mt("Negative","ঋণাত্মক"),same("96")],
          [same("Verification status"),same("Pending"),same("74")],
          [same("Verification status"),same("Verified"),same("22")],
          [same("Verification status"),same("Partially"),same("9")],
          [same("Verification status"),same("Refuted"),same("6")],
          [same("Verification status"),same("Unable"),same("3")],
        ],
      },
      {
        kind: "table",
        title: mt("Reconciliation calculator presets","Reconciliation calculator preset"),
        columns: [mt("Preset","Preset"), same("1(a) inc"), same("1(b) exm"), same("1(c) rec"), same("2 prev"), same("4(a) bb"), same("4(b) oth"), same("6 lia"), same("10 ast"), mt("Prior line 5","Prior line 5")],
        rows: [
          [mt("Balanced salaried","Balanced salaried"),same("12"),same("0.5"),same("0"),same("30"),same("6"),same("0"),same("0"),same("36.5"),same("30")],
          [mt("Asset-driven gap","Asset-driven gap"),same("8"),same("0"),same("0"),same("31"),same("4.5"),same("0"),same("0"),same("82"),same("31")],
          [mt("Expenditure-driven","Expenditure-driven"),same("6"),same("0"),same("0"),same("25"),same("14"),same("0"),same("0"),same("26"),same("25")],
          [mt("Loan-funded flat","Loan-funded flat"),same("15"),same("0"),same("0"),same("20"),same("9.5"),same("0"),same("55"),same("80.5"),same("20")],
          [mt("Declared inheritance","Declared inheritance"),same("4.5"),same("0"),same("67"),same("3"),same("3.5"),same("0"),same("0"),same("71"),same("3")],
          [mt("Negative gap","Negative gap"),same("12"),same("0"),same("0"),same("30"),same("6"),same("0"),same("0"),same("30"),same("30")],
          [mt("IT-10BB blank","IT-10BB blank"),same("7"),same("0"),same("0"),same("25"),same("blank"),same("0"),same("0"),same("39"),same("25")],
          [mt("Invalid numeric","Invalid numeric"),same("12a"),same("0"),same("0"),same("25"),same("5"),same("0"),same("0"),same("32"),same("25")],
          [mt("Continuity break","Continuity break"),same("12"),same("0.5"),same("0"),same("30"),same("6"),same("0"),same("0"),same("36.5"),same("22")],
        ],
        note: mt("All monetary preset values are in lakh BDT in the source calculator.","Source calculator-এর সব monetary preset value lakh BDT।"),
      },
      {
        kind: "table",
        title: mt("Demo case 1 — asset-driven gap","Demo case 1 — asset-driven gap"),
        columns: [mt("Data group","Data group"), mt("Source demo values","Source demo value")],
        rows: [
          [same("Identity"),same("DEMO-1 · TIN ••••4821 · AY 2023-24 · tier DT2")],
          [same("Return"),same("income 8 · tax 0.5")],
          [same("Current reconciliation input"),same("inc 8 · exm 0 · rec 0 · prev 31 · bb 4.5 · oth 0 · lia 0 · ast 82")],
          [same("Previous reconciliation input"),same("inc 7.5 · exm 0 · rec 0 · prev 27 · bb 4.2 · oth 0 · lia 0 · ast 31")],
          [same("History 2020-21"),same("inc 6.8 · tax 0.35 · exp 3.9 · nw 24 · gross 24 · ast 24")],
          [same("History 2021-22"),same("inc 7.2 · tax 0.4 · exp 4.0 · nw 27 · gross 27 · ast 27")],
          [same("History 2022-23"),same("inc 7.5 · tax 0.42 · exp 4.2 · nw 31 · gross 31 · ast 31")],
          [same("History 2023-24"),same("inc 8.0 · tax 0.5 · exp 4.5 · nw 34.5 · gross 34.5 · ast 82")],
          [mt("Current assets","Current asset"),mt("Business 8a 0 · non-agri property 8d 58 · agricultural land 8e 2 · financial asset 8f 9 · vehicle 8g 7 · household 8i/8j 3 · cash/bank 8k 3 · foreign 9 0","Business 8a 0 · non-agri property 8d 58 · agricultural land 8e 2 · financial asset 8f 9 · vehicle 8g 7 · household 8i/8j 3 · cash/bank 8k 3 · foreign 9 0")],
          [mt("Previous assets","Previous asset"),mt("Business 8a 0 · non-agri property 8d 14 · agricultural land 8e 2 · financial asset 8f 8 · vehicle 8g 0 · household 8i/8j 3 · cash/bank 8k 4 · foreign 9 0","Business 8a 0 · non-agri property 8d 14 · agricultural land 8e 2 · financial asset 8f 8 · vehicle 8g 0 · household 8i/8j 3 · cash/bank 8k 4 · foreign 9 0")],
          [mt("Current expenditure components","Current expenditure component"),mt("Housing 1.2 · vehicle 0.7 · education 0.6 · food/clothing 0.9 · utility 0.35 · festival 0.2 · travel 0.15 · Sl.8 TDS/prior tax 0.4","Housing 1.2 · vehicle 0.7 · education 0.6 · food/clothing 0.9 · utility 0.35 · festival 0.2 · travel 0.15 · Sl.8 TDS/prior tax 0.4")],
          [mt("Previous expenditure components","Previous expenditure component"),mt("Housing 1.1 · vehicle 0.2 · education 0.6 · food/clothing 0.9 · utility 0.32 · festival 0.2 · travel 0.45 · Sl.8 TDS/prior tax 0.43","Housing 1.1 · vehicle 0.2 · education 0.6 · food/clothing 0.9 · utility 0.32 · festival 0.2 · travel 0.45 · Sl.8 TDS/prior tax 0.43")],
          [same("Seed signals"),same("R-B1 meaningful · fact asset-growth · family internal-change")],
          [same("Control flags"),same("F1")],
          [same("Engine outcome"),mt("Reconciliation: Sources 8, Uses 4.5, Net/Gross Wealth 34.5, Assets 82, Gap +47.5, materiality 2 → auto R-C1 strong; B1 becomes context; Risk Level High.","Reconciliation: Sources 8, Uses 4.5, Net/Gross Wealth 34.5, Assets 82, Gap +47.5, materiality 2 → auto R-C1 strong; B1 context; Risk Level High।")],
          [mt("Source correction note","Source correction note"),mt("The source comments that R-A1 must not fire because income is 8L, not zero; only B1 is seeded before reconciliation.","Source comment: income 8L হওয়ায় R-A1 fire নয়; reconciliation-এর আগে শুধু B1 seed।")],
        ],
      },
      {
        kind: "table",
        title: mt("Demo case 2 — reconciled salaried","Demo case 2 — reconciled salaried"),
        columns: [mt("Data group","Data group"), mt("Source demo values","Source demo value")],
        rows: [
          [same("Identity"),same("DEMO-2 · TIN ••••7310 · AY 2023-24 · tier DT1+H")],
          [same("Return"),same("income 12 · tax 0.95")],
          [same("Current reconciliation input"),same("inc 12 · exm 0.5 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36.5")],
          [same("Previous reconciliation input"),same("inc 11 · exm 0.4 · rec 0 · prev 25 · bb 5.8 · oth 0 · lia 0 · ast 30")],
          [same("History 2021-22"),same("inc 10.2 · tax 0.72 · exp 5.4 · nw 21 · gross 21 · ast 21")],
          [same("History 2022-23"),same("inc 11.0 · tax 0.8 · exp 5.8 · nw 25 · gross 25 · ast 25")],
          [same("History 2023-24"),same("inc 12.0 · tax 0.95 · exp 6.0 · nw 36.5 · gross 36.5 · ast 36.5")],
          [same("Component data"),mt("Asset components: unavailable · expenditure components: unavailable","Asset component: unavailable · expenditure component: unavailable")],
          [same("Seed signals"),same("none")],
          [same("Control flags"),same("none")],
          [same("Engine outcome"),mt("Reconciliation gap 0; no substantive signal retained; Risk Level Low.","Reconciliation gap 0; retained substantive signal নেই; Risk Level Low।")],
        ],
      },
      {
        kind: "table",
        title: mt("Demo case 3 — return only","Demo case 3 — return only"),
        columns: [mt("Data group","Data group"), mt("Source demo values","Source demo value")],
        rows: [
          [same("Identity"),same("DEMO-3 · TIN ••••1902 · AY 2023-24 · tier DT0")],
          [same("Return"),same("income 4.2 · tax 0")],
          [same("IT-10B / history / components"),mt("Unavailable","Unavailable")],
          [same("Seed signals"),same("R-A2 weak · fact tax-zero · family internal-tax")],
          [same("Control flags"),same("F5")],
          [same("Engine outcome"),mt("No reconciliation because IT-10B is unavailable; R-A2 weak remains eligible from return data; Risk Level Low, with F5 on the separate control path.","IT-10B unavailable বলে reconciliation নেই; return data থেকে R-A2 weak eligible; Risk Level Low, F5 আলাদা control path-এ।")],
        ],
      },
    ],
  },
];

export const AUDIT_MANUAL_DEMO_SUPPLEMENTS: Record<string, ManualBlock[]> = {
  s06: [
    {
      kind: "matrix",
      title: mt("Generated matrix — Net Wealth increased / unchanged","Generated matrix — Net Wealth বেড়েছে / অপরিবর্তিত"),
      modeLabels: [mt("Net Wealth ↑ / flat","Net Wealth ↑ / flat")],
      rowLabels: ["I0 = 0","I1 ≤3L","I2 3–5L","I3 5–10L","I4 10–25L","I5 >25L"],
      columnLabels: ["E0 = 0","E1 ≤3L","E2 3–6L","E3 6–12L","E4 12–30L","E5 >30L"],
      values: [[
        ["PC","P2","P2","P3","P3","P3"],
        ["PC","P1","P3","P3","P3","P3"],
        ["PC","P0","P2","P3","P3","P3"],
        ["PC","P1","P1","P2","P3","P3"],
        ["PC","P1","P0","P0","P2","P3"],
        ["PC","P1","P0","P0","P0","P2"],
      ]],
      legend: {
        PC: mt("Coverage / Data Quality","Coverage / Data Quality"),
        P0: mt("Ordinary","Ordinary"),
        P1: mt("Attention","Attention"),
        P2: mt("Elevated","Elevated"),
        P3: mt("Strong screening priority","Strong screening priority"),
      },
      note: mt("The source generates these cells from income/expenditure midpoints and the ieLevel() logic; they are priority, not findings.","Source income/expenditure midpoint ও ieLevel() logic থেকে cell generate করে; এগুলো priority, finding নয়।"),
    },
    {
      kind: "matrix",
      title: mt("Generated matrix — Net Wealth decreased","Generated matrix — Net Wealth কমেছে"),
      modeLabels: [mt("Net Wealth ↓","Net Wealth ↓")],
      rowLabels: ["I0 = 0","I1 ≤3L","I2 3–5L","I3 5–10L","I4 10–25L","I5 >25L"],
      columnLabels: ["E0 = 0","E1 ≤3L","E2 3–6L","E3 6–12L","E4 12–30L","E5 >30L"],
      values: [[
        ["PC","P1","P1","P1","P2","P2"],
        ["PC","P0","P2","P2","P2","P2"],
        ["PC","P0","P1","P1","P2","P2"],
        ["PC","P1","P0","P1","P1","P2"],
        ["PC","P1","P0","P0","P1","P1"],
        ["PC","P1","P0","P0","P0","P1"],
      ]],
      legend: {
        PC: mt("Coverage / Data Quality","Coverage / Data Quality"),
        P0: mt("Ordinary","Ordinary"),
        P1: mt("Attention","Attention"),
        P2: mt("Elevated","Elevated"),
        P3: mt("Strong screening priority","Strong screening priority"),
      },
    },
    {
      kind: "formula",
      title: mt("Exact ieLevel() source logic","Exact ieLevel() source logic"),
      lines: [
        same("Income midpoints: [0, 1.5, 4, 7.5, 17.5, 40] lakh"),
        same("Expenditure midpoints: [0, 1.5, 4.5, 9, 21, 45] lakh"),
        mt("If E0 → PC (Coverage/Data Quality), not a risk priority.","E0 → PC (Coverage/Data Quality), risk priority নয়।"),
        mt("If Net Wealth rises/flat: I0 → P3 when expenditure midpoint ≥9 else P2; otherwise expenditure ≥2× income → P3; > income → P2; ≥60% income → P1; E1 with I3+ → P1; else P0.","Net Wealth ↑/flat: I0 হলে exp midpoint ≥9 → P3, নইলে P2; অন্যথায় exp ≥2×income → P3; >income → P2; ≥60% → P1; E1 ও I3+ → P1; else P0।"),
        mt("If Net Wealth falls: I0 → P2 when expenditure midpoint ≥21 else P1; otherwise expenditure ≥3× income → P2; > income → P1; E1 with I3+ → P1; else P0.","Net Wealth ↓: I0 হলে exp midpoint ≥21 → P2, নইলে P1; অন্যথায় exp ≥3×income → P2; >income → P1; E1 ও I3+ → P1; else P0।"),
      ],
    },
  ],
  s13: [
    {
      kind: "table",
      title: mt("Source verification-strip demo", "Source verification-strip demo"),
      columns: [mt("State","State"), mt("Risk / signals","Risk / signals"), mt("Verification","Verification"), mt("Evidence refs","Evidence ref"), mt("Meaning","Meaning")],
      rows: [
        [mt("Before verification","Verification-এর আগে"),same("Risk High · R-C1 strong · R-E2 meaningful · R-D3 weak"),same("C1 Pending · E2 Pending · D3 Pending"),same("none"),mt("Three signals are open; Risk Level already comes from the screening engine.","তিন signal open; Risk Level screening engine থেকেই এসেছে।")],
        [mt("After partial verification","আংশিক verification-এর পরে"),same("Risk remains High"),same("C1 Verified · E2 Refuted · D3 Pending"),same("C1: D-1 Bank statement · E2: D-2 Registry extract"),mt("One signal's outcome does not alter another signal, and verification does not change Risk Level.","এক signal-এর outcome অন্য signal-কে স্পর্শ করে না; verification Risk Level বদলায় না।")],
      ],
    },
  ],
  s07: [
    {
      kind: "table",
      title: mt("Reconciliation preset source values","Reconciliation preset source value"),
      columns: [mt("Preset","Preset"), mt("Input tuple","Input tuple")],
      rows: [
        [same("Balanced salaried"),same("inc12, exm0.5, rec0, prev30, bb6, oth0, lia0, ast36.5, prior line5=30")],
        [same("Asset-driven gap"),same("inc8, exm0, rec0, prev31, bb4.5, oth0, lia0, ast82, prior line5=31")],
        [same("Expenditure-driven"),same("inc6, exm0, rec0, prev25, bb14, oth0, lia0, ast26, prior line5=25")],
        [same("Loan-funded flat"),same("inc15, exm0, rec0, prev20, bb9.5, oth0, lia55, ast80.5, prior line5=20")],
        [same("Declared inheritance"),same("inc4.5, exm0, rec67, prev3, bb3.5, oth0, lia0, ast71, prior line5=3")],
        [same("Negative gap"),same("inc12, exm0, rec0, prev30, bb6, oth0, lia0, ast30, prior line5=30")],
        [same("IT-10BB blank"),same("inc7, exm0, rec0, prev25, bb=blank, oth0, lia0, ast39, prior line5=25")],
        [same("Invalid"),same("inc='12a', exm0, rec0, prev25, bb5, oth0, lia0, ast32, prior line5=25")],
        [same("Continuity break"),same("inc12, exm0.5, rec0, prev30, bb6, oth0, lia0, ast36.5, prior line5=22")],
      ],
    },
  ],
};
