import type { TableRow } from "../modulePageUtils";

export const RISK_CASE_ROWS: TableRow[] = [
  { id:"1", case_id:"CASE-2026-001", return_id:"RET-2026-10482", tin:"******4821", assessment_year:"2025-26", return_version:"v1", circle:"Circle-1", coverage_tier:"DT3", risk_level:"Very High", signals:"R-C1 (strong) + R-E2 (meaningful, independent external family)", verification_summary:"R-C1 Verified; R-E2 Pending", evidence_status:"Evidence Pending", evidence_refs:"Bank statement REF-101; Registry extract requested", finding_status:"Locked", sla:"1 working day (proposed)", case_status:"Evidence Pending", assigned_to:"DCT — Circle-1", reason_code:"Independent funds-flow + registry corroboration" },
  { id:"2", case_id:"CASE-2026-002", return_id:"RET-2026-10491", tin:"******4917", assessment_year:"2025-26", return_version:"v1", circle:"Circle-1", coverage_tier:"DT1", risk_level:"High", signals:"R-C1 (strong reconciliation gap)", verification_summary:"Verification in progress", evidence_status:"Pending", evidence_refs:"Evidence checklist issued for R-C1", finding_status:"Locked", sla:"3 working days (proposed)", case_status:"Verifying", assigned_to:"DCT — Circle-1", reason_code:"Single strong signal" },
  { id:"3", case_id:"CASE-2026-003", return_id:"RET-2026-10502", tin:"******5024", assessment_year:"2025-26", return_version:"v2", circle:"Circle-1", coverage_tier:"DT2", risk_level:"High", signals:"R-B1 + R-C1 after deduplication", verification_summary:"R-C1 Verified; overlapping signal retained as context", evidence_status:"Verified", evidence_refs:"Acquisition record REF-208; Bank statement REF-209", finding_status:"Available", sla:"3 working days (proposed)", case_status:"Ready for Review", assigned_to:"DCT — Circle-1", reason_code:"Deduplicated independent assessment" },
  { id:"4", case_id:"CASE-2026-004", return_id:"RET-2026-10517", tin:"******5176", assessment_year:"2025-26", return_version:"v1", circle:"Circle-1", coverage_tier:"DT1", risk_level:"Medium", signals:"R-C1 (meaningful)", verification_summary:"R-C1 Partially verified", evidence_status:"Partial", evidence_refs:"Taxpayer explanation REF-311", finding_status:"Locked", sla:"Standard review", case_status:"Verifying", assigned_to:"DCT — Circle-1", reason_code:"One meaningful signal" },
  { id:"5", case_id:"CASE-2026-005", return_id:"RET-2026-10528", tin:"******5283", assessment_year:"2025-26", return_version:"v1", circle:"Circle-1", coverage_tier:"DT0", risk_level:"Low", signals:"R-A2 (weak)", verification_summary:"Pending", evidence_status:"Not requested", evidence_refs:"—", finding_status:"Locked", sla:"Routine queue", case_status:"Assigned", assigned_to:"DCT — Circle-1", reason_code:"One weak eligible signal; Low is priority only, not a compliance conclusion" },
  { id:"6", case_id:"CASE-2026-006", return_id:"RET-2026-10539", tin:"******5398", assessment_year:"2025-26", return_version:"v1", circle:"Circle-1", coverage_tier:"DT3", risk_level:"Very High", signals:"R-C1 (strong) + R-E1 (meaningful, independent external family)", verification_summary:"Both signals Verified", evidence_status:"Verified", evidence_refs:"Bank statement REF-410; Payroll extract REF-412", finding_status:"Submitted", sla:"1 working day (proposed)", case_status:"Second Review", assigned_to:"Range Officer review queue", reason_code:"Strong internal signal plus independent external corroboration" },
  { id:"7", case_id:"CASE-2026-007", return_id:"RET-2026-10544", tin:"******5442", assessment_year:"2025-26", return_version:"v1", circle:"Circle-1", coverage_tier:"DT2", risk_level:"High", signals:"R-C2 (strong multi-year cumulative gap)", verification_summary:"Verified", evidence_status:"Verified", evidence_refs:"Multi-year reconciliation REF-501", finding_status:"Submitted", sla:"3 working days (proposed)", case_status:"Rework Requested", assigned_to:"DCT — Circle-1", reason_code:"Second review requested additional verification basis" },
  { id:"8", case_id:"CASE-2026-008", return_id:"RET-2026-10558", tin:"******5589", assessment_year:"2025-26", return_version:"v2", circle:"Circle-1", coverage_tier:"DT2", risk_level:"Medium", signals:"R-D3 (meaningful amendment timing)", verification_summary:"Refuted", evidence_status:"Verified", evidence_refs:"Amendment explanation REF-611", finding_status:"Locked", sla:"Standard review", case_status:"Closed", assigned_to:"DCT — Circle-1", reason_code:"No discrepancy established after verification" },
];

export const CONTROL_ROWS: TableRow[] = [
  { id:"1", return_id:"RET-2026-20401", tin:"******4012", assessment_year:"2025-26", circle:"Circle-1", coverage_tier:"DT1", flag_id:"F0", check:"Form arithmetic consistency", source:"Return + IT-10B", dependency:"Deterministic; no external dependency", queue:"Data Quality / Control", control_status:"Pending" },
  { id:"2", return_id:"RET-2026-20407", tin:"******4075", assessment_year:"2025-26", circle:"Circle-1", coverage_tier:"DT1", flag_id:"F1", check:"Return Sl. 11 / Sl. 26 consistency with IT-10B 1(a) / 1(b)", source:"Return ↔ IT-10B", dependency:"Both statements required (DT1)", queue:"Control", control_status:"In Progress" },
  { id:"3", return_id:"RET-2026-20411", tin:"******4119", assessment_year:"2025-26", circle:"Circle-1", coverage_tier:"DT1", flag_id:"F2", check:"Net wealth over surcharge threshold while Return Sl. 17(a) is zero", source:"IT-10B 5 ↔ Return 17(a)", dependency:"Threshold/base requires Finance Act confirmation", queue:"Control", control_status:"Pending Review" },
  { id:"4", return_id:"RET-2026-20416", tin:"******4163", assessment_year:"2025-26", circle:"Circle-1", coverage_tier:"DT2", flag_id:"F3", check:"Schedule 4 Drawing vs IT-10BB; Closing Capital vs IT-10B 8(a)", source:"Schedule 4 ↔ IT-10B / IT-10BB", dependency:"Business return + DT2 component data", queue:"Control", control_status:"In Progress" },
  { id:"5", return_id:"RET-2026-20422", tin:"******4228", assessment_year:"2025-26", circle:"Circle-1", coverage_tier:"DT2", flag_id:"F4", check:"Schedule 5 investment not reflected in financial asset / expenditure", source:"Schedule 5 ↔ IT-10B 8(f)", dependency:"DT2 component data; life insurance premium is not treated as asset", queue:"Control", control_status:"Resolved" },
  { id:"6", return_id:"RET-2026-20429", tin:"******4291", assessment_year:"2025-26", circle:"Circle-1", coverage_tier:"DT0", flag_id:"F5", check:"Required IT-10B / IT-10BB statement appears to be missing", source:"Form-described filing trigger", dependency:"Trigger evidence remains unresolved in source framework", queue:"Compliance", control_status:"Under Review" },
];

export const SECOND_REVIEW_ROWS: TableRow[] = [
  { id:"1", case_id:"CASE-2026-006", return_id:"RET-2026-10539", tin:"******5398", risk_level:"Very High", primary_signal:"R-C1 + R-E1", verification_basis:"Both signals Verified", evidence_refs:"REF-410; REF-412", finding_summary:"Finding references the verified signals and linked evidence", submitted_by:"DCT — Circle-1", review_status:"Ready for Review", permitted_actions:"Sign off / Request rework" },
  { id:"2", case_id:"CASE-2026-003", return_id:"RET-2026-10502", tin:"******5024", risk_level:"High", primary_signal:"R-C1", verification_basis:"R-C1 Verified; overlapping signal retained as context", evidence_refs:"REF-208; REF-209", finding_summary:"Finding supported by R-C1 evidence", submitted_by:"DCT — Circle-1", review_status:"Second Review", permitted_actions:"Sign off / Request rework" },
  { id:"3", case_id:"CASE-2026-007", return_id:"RET-2026-10544", tin:"******5442", risk_level:"High", primary_signal:"R-C2", verification_basis:"Verified, but review basis requires clarification", evidence_refs:"REF-501", finding_summary:"Returned for more specific verification basis", submitted_by:"DCT — Circle-1", review_status:"Rework Requested", permitted_actions:"Await revised verification trail" },
];

export const RULE_ROWS: TableRow[] = [
  { id:"1", rule_id:"R-C1", version:"v3", rule_family:"Funds-flow Reconciliation", author_role:"DCT", plain_language_condition:"Flag a material reconciliation gap between independently declared assets and funds-flow wealth.", dry_run_status:"Completed", governance_status:"Awaiting Endorsement", mode:"Draft", rollout_scope:"Not set", version_note:"New version; previous version remains in history" },
  { id:"2", rule_id:"R-E2", version:"v2", rule_family:"External Cross-check", author_role:"DCT", plain_language_condition:"Compare permitted asset-registry data with declared assets.", dry_run_status:"Completed", governance_status:"Awaiting Approval", mode:"Draft", rollout_scope:"Not set", version_note:"Requires legal basis for external source" },
  { id:"3", rule_id:"R-A2", version:"v4", rule_family:"Basic Anomaly", author_role:"DCT", plain_language_condition:"Income declared while tax payable is zero; strength varies by configured band.", dry_run_status:"Completed", governance_status:"Approved", mode:"Shadow", rollout_scope:"Record only; no case routing", version_note:"Shadow evaluation" },
  { id:"4", rule_id:"R-D3", version:"v2", rule_family:"Behavioural Pattern", author_role:"DCT", plain_language_condition:"Identify revised returns filed within the configured period after a trigger.", dry_run_status:"Completed", governance_status:"Approved", mode:"Staged", rollout_scope:"25% of approved scope", version_note:"Staged rollout" },
  { id:"5", rule_id:"R-C2", version:"v5", rule_family:"Funds-flow Reconciliation", author_role:"DCT", plain_language_condition:"Detect a material multi-year cumulative reconciliation gap.", dry_run_status:"Completed", governance_status:"Approved", mode:"Live", rollout_scope:"Approved scope", version_note:"Current live version" },
  { id:"6", rule_id:"R-C2", version:"v4", rule_family:"Funds-flow Reconciliation", author_role:"DCT", plain_language_condition:"Earlier cumulative-gap definition.", dry_run_status:"Completed", governance_status:"Superseded", mode:"Superseded", rollout_scope:"Historical only", version_note:"Never edited in place; superseded by v5" },
];

export const RECONCILIATION_ROWS: TableRow[] = [
  { id:"1", reconciliation_date:"2026-09-28", scope:"Range-1", high_risk_returns:"12", matching_cases:"12", missing_case_count:"0", reconciliation_status:"Matched", supervisor_view:"Range Officer" },
  { id:"2", reconciliation_date:"2026-09-28", scope:"Range-2", high_risk_returns:"9", matching_cases:"8", missing_case_count:"1", reconciliation_status:"Missing Case", supervisor_view:"Range Officer" },
  { id:"3", reconciliation_date:"2026-09-28", scope:"Zone summary", high_risk_returns:"31", matching_cases:"30", missing_case_count:"1", reconciliation_status:"Under Review", supervisor_view:"Commissioner" },
  { id:"4", reconciliation_date:"2026-09-27", scope:"Range-1", high_risk_returns:"11", matching_cases:"11", missing_case_count:"0", reconciliation_status:"Matched", supervisor_view:"Range Officer" },
];

export const AUDIT_TRAIL_ROWS: TableRow[] = [
  { id:"1", event_id:"EVT-90001", timestamp_utc:"2026-09-28 02:15:12 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0142", actor_role:"DCT", action:"Case created from reconciled risk selection", data_state:"COMPLETE / DT3", assessment:"R-C1 v3 + R-E1 v1; Very High", human_record:"—", access_record:"—", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
  { id:"2", event_id:"EVT-90002", timestamp_utc:"2026-09-28 02:31:48 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0142", actor_role:"DCT", action:"Evidence linked to R-C1", data_state:"No overwrite", assessment:"R-C1", human_record:"Bank statement REF-410 linked to signal", access_record:"—", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
  { id:"3", event_id:"EVT-90003", timestamp_utc:"2026-09-28 03:04:21 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0142", actor_role:"DCT", action:"Signal verification recorded", data_state:"No overwrite", assessment:"R-C1 strong", human_record:"Verified with reason and evidence REF-410", access_record:"—", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
  { id:"4", event_id:"EVT-90004", timestamp_utc:"2026-09-28 03:22:09 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0142", actor_role:"DCT", action:"Sensitive field reveal", data_state:"No assessment change", assessment:"—", human_record:"—", access_record:"Purpose code recorded; specific fields logged", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
  { id:"5", event_id:"EVT-90005", timestamp_utc:"2026-09-28 04:11:33 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0142", actor_role:"DCT", action:"Finding submitted", data_state:"No overwrite", assessment:"Very High unchanged", human_record:"Finding supported by R-C1 + R-E1 and linked evidence", access_record:"—", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
  { id:"6", event_id:"EVT-90006", timestamp_utc:"2026-09-28 05:08:16 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0028", actor_role:"Range Officer", action:"Second review sign-off", data_state:"No overwrite", assessment:"Very High unchanged", human_record:"Reviewed named signals and evidence; sign-off recorded", access_record:"—", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
  { id:"7", event_id:"EVT-90007", timestamp_utc:"2026-09-28 05:14:40 UTC", return_id:"RET-2026-10539", return_version:"v1", actor_id:"OFF-0028", actor_role:"Range Officer", action:"Case closed", data_state:"No overwrite", assessment:"Original assessment retained", human_record:"Closure reason recorded", access_record:"—", classification_version:"CV-2026.2", rule_config_version:"RCV-44" },
];

export const RISK_DISTRIBUTION_ROWS: TableRow[] = [
  { id:"1", risk_level:"Low", case_count:"18", handling:"Routine queue" },
  { id:"2", risk_level:"Medium", case_count:"24", handling:"Standard review" },
  { id:"3", risk_level:"High", case_count:"11", handling:"Proposed target: 3 working days" },
  { id:"4", risk_level:"Very High", case_count:"4", handling:"Proposed target: 1 working day" },
];

export const QUEUE_HEALTH_ROWS: TableRow[] = [
  { id:"1", queue:"Risk Cases", open_items:"38", waiting_on:"Officer / evidence / review", queue_status:"In Progress" },
  { id:"2", queue:"Control & Data Quality", open_items:"16", waiting_on:"Data correction / control review", queue_status:"In Progress" },
  { id:"3", queue:"Second Review", open_items:"7", waiting_on:"Range Officer", queue_status:"Pending Review" },
  { id:"4", queue:"Daily Reconciliation", open_items:"1", waiting_on:"Missing case resolution", queue_status:"Under Review" },
];

export const ROLE_SCOPE_ROWS: TableRow[] = [
  { id:"1", role:"DCT", jurisdiction:"Own Circle", primary_audit_work:"Risk/Control queues, evidence, verification, Findings, Rule Studio authoring", data_access:"Masked by default; logged reveal with reason" },
  { id:"2", role:"Range Officer", jurisdiction:"Range", primary_audit_work:"Second review, SLA/escalation oversight, reconciliation, rule endorsement", data_access:"Masked by default; logged reveal" },
  { id:"3", role:"Commissioner of Taxes", jurisdiction:"Zone", primary_audit_work:"Aggregate dashboard, final rule approval, high-sensitivity export approval", data_access:"Aggregate by default; case reveal only if justified and logged" },
  { id:"4", role:"Internal Audit / Vigilance", jurisdiction:"Cross-cutting", primary_audit_work:"Audit trail, access logs, reconciliation review", data_access:"Read-only; fully logged" },
  { id:"5", role:"SuperAdmin", jurisdiction:"System-wide administration", primary_audit_work:"Accounts, roles and system configuration only", data_access:"No case-data access" },
];
