import { mt, type ManualBlock, type ManualSection } from "./auditManualTypes";

const same = (v: string) => mt(v, v);

export const AUDIT_MANUAL_TEST_SECTIONS: ManualSection[] = [
  {
    id: "s12",
    number: "12",
    area: "testing",
    sourceOrder: "Reference",
    title: mt("Test Cases and Self-test", "Test Cases ও Self-test"),
    description: mt(
      "The source computes every test-case Level through riskLevel(); expected Levels are not independently hard-coded into the displayed logic. Case details also preserve IT-10B inputs, flags, expected action and false-positive commentary.",
      "Source প্রতিটি test-case Level riskLevel() দিয়ে compute করে; displayed logic-এ আলাদা level function নেই। Case detail-এ IT-10B input, flag, expected action ও false-positive comment সংরক্ষিত।"
    ),
    keywords: ["test cases","self test","tc01","tc22","pass","false positive","expected"],
    blocks: [
      {
        kind: "table",
        title: mt("Twenty-two source test cases", "Source-এর ২২টি test case"),
        columns: [
          same("Case"), mt("Scenario","Scenario"), mt("Coverage input","Coverage input"), mt("IT-10B / return inputs (lakh)","IT-10B / return input (লাখ)"),
          mt("Seed signals / flags","Seed signal / flag"), mt("Expected Level","Expected Level"), mt("Human next action","মানুষের পরবর্তী পদক্ষেপ"), mt("FP / limitation note","FP / limitation note")
        ],
        rows: [
          [same("TC01 · adv A"),mt("Legitimate inheritance declared in 1(c)","বৈধ উত্তরাধিকার — 1(c)-তে ঘোষিত"),same("filed"),same("inc 4.5 · exm 0 · rec 67 · prev 3 · bb 3.5 · oth 0 · lia 0 · ast 71 · prior line5 3"),same("R-B1 meaningful · no flags"),same("Low"),mt("No action; deed may be checked on a sample basis.","কোনো পদক্ষেপ নয়; sample basis-এ deed যাচাই হতে পারে।"),mt("Avoided: receipt is declared, so gap is zero.","✓ এড়ানো গেছে — receipt ঘোষিত, gap zero।")],
          [same("TC02 · adv B"),mt("Flat purchased with legitimate large loan","বৈধ বড় ঋণে কেনা ফ্ল্যাট"),same("filed"),same("inc 15 · exm 0 · rec 0 · prev 20 · bb 9.5 · oth 0 · lia 55 · ast 80.5 · prior line5 20"),same("R-B1 meaningful · no flags"),same("Low"),mt("No action.","কোনো পদক্ষেপ নয়।"),mt("Avoided: line 6 liability makes gap zero; DT0 could falsely flag it.","✓ liability line 6-এ, gap zero; DT0-তে ভুল flag হতে পারত।")],
          [same("TC03 · adv C"),mt("Spending funded by drawing down old savings","পুরনো সঞ্চয় ভেঙে খরচ"),same("filed"),same("inc 2 · exm 0 · rec 0 · prev 60 · bb 12 · oth 0 · lia 0 · ast 50 · prior line5 60"),same("No seed signal · no flags"),same("Low"),mt("No action.","কোনো পদক্ষেপ নয়।"),mt("Asset reduction explains expenditure.","✓ asset reduction expenditure explain করে।")],
          [same("TC04 · adv D"),mt("Retiree with pension declared as exempt","অবসরভোগী — pension exempt"),same("filed"),same("inc 0 · exm 6 · rec 0 · prev 140 · bb 5.5 · oth 0 · lia 0 · ast 140.5 · prior line5 140"),same("R-A1 strong + R-D1 weak · no flags"),same("Low"),mt("No action.","কোনো পদক্ষেপ নয়।"),mt("A1 becomes context when reconciliation runs; D1 is the same fact and not counted separately.","✓ A1 context; D1 same fact — আলাদা count নয়।")],
          [same("TC05 · adv E"),mt("Homemaker, joint property; IT-10B not required","গৃহিণী, যৌথ সম্পত্তি — IT-10B required নয়"),same("not-required"),same("No IT-10B inputs"),same("No signals · no flags"),mt("Undetermined","নির্ণয় হয়নি"),mt("No action; keep visible as limited coverage.","কোনো পদক্ষেপ নয়; coverage সীমিত হিসেবে visible।"),mt("Not labelled Low because the data is absent.","✓ Data নেই বলে Low বলা হয়নি।")],
          [same("TC06 · adv F"),mt("First-time filer with large asset","প্রথমবার filer, বড় asset"),same("filed-partial"),same("inc 0 · exm 0 · rec 0 · prev NULL · bb 4 · oth 0 · lia 0 · ast 120"),same("R-A1 strong · no flags"),same("High"),mt("Request wealth-source statement; C1 cannot run because opening NW is missing.","Wealth-source statement; opening NW নেই বলে C1 চলে না।"),mt("A1 remains a proxy with high FP risk because reconciliation is impossible.","⚠ A1 proxy; reconciliation অসম্ভব, FP risk বেশি।")],
          [same("TC07 · adv G"),mt("IT-10BB blank","IT-10BB ফাঁকা"),same("filed-partial"),same("inc 4.8 · exm 0 · rec 0 · prev 25 · bb NULL · oth 0 · lia 0 · ast 39"),same("R-B1 meaningful · F0"),same("Medium"),mt("Request DQ correction; B1 continues as a proxy with incomplete tag.","DQ correction; B1 proxy incomplete tag সহ।"),mt("Missing component was not treated as zero; no artificial gap.","✓ Missing = zero নয়; artificial gap নেই।")],
          [same("TC08 · adv H"),mt("IT-10B missing despite obligation — vehicle owner","Obligation থাকা সত্ত্বেও IT-10B নেই — car owner"),same("missing"),same("No IT-10B inputs"),same("No signals · F5"),mt("Undetermined","নির্ণয় হয়নি"),mt("Compliance queue — request statement.","Compliance queue — statement চাওয়া।"),mt("Control flag did not become risk and case was not labelled Low.","✓ F5 risk নয়; Low-ও বলা হয়নি।")],
          [same("TC09 · adv I"),mt("Inflated liability","অতিরঞ্জিত liability"),same("filed"),same("inc 6 · exm 0 · rec 0 · prev 20 · bb 5 · oth 0 · lia 40 · ast 61 · prior line5 20"),same("No signals · no flags"),same("Low"),mt("No signal — recognized framework weakness, Loophole 6.","কোনো signal নয় — Loophole 6 recognized weakness।"),mt("Fictitious loan can close the gap unless lender is verified.","⚠ Fake loan gap বন্ধ করে; lender verification দরকার।")],
          [same("TC10 · adv J"),mt("Cash in hand used as balancing figure","Cash in hand দিয়ে হিসাব মেলানো"),same("filed"),same("inc 5 · exm 0 · rec 0 · prev 25 · bb 3 · oth 0 · lia 0 · ast 27 · prior line5 25"),same("No signals · no flags"),same("Low"),mt("Invisible without DT2 component analysis.","DT2 component analysis ছাড়া invisible।"),mt("Gap is zero; detecting a jump in 8(k)(ii) needs a component rule not yet defined.","⚠ Gap zero; 8(k)(ii) jump ধরতে component rule এখনো নেই।")],
          [same("TC11 · adv K"),mt("Understated expenditure","খরচ কম দেখানো"),same("filed"),same("inc 9 · exm 0 · rec 0 · prev 40 · bb 0.4 · oth 0 · lia 0 · ast 48.6 · prior line5 40"),same("R-C4 meaningful · no flags"),same("Medium"),mt("Verify household composition; subject to approved floor policy.","Household composition verify; floor policy সাপেক্ষে।"),mt("C4 cannot run until the floor is defined by policy.","⚠ Floor policy-defined না হলে C4 চালানো যাবে না।")],
          [same("TC12 · adv L"),mt("Understated asset — negative gap","সম্পদ কম দেখানো — negative gap"),same("filed"),same("inc 12 · exm 0 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 28 · prior line5 30"),same("No seed signals · no flags"),same("Medium"),mt("Check undeclared gift/loss in 4(b) or omitted asset.","4(b)-তে undeclared gift/loss নাকি asset missing দেখুন।"),mt("Negative gap is interpreted separately from positive gap.","✓ Negative gap positive-এর মতো নয়।")],
          [same("TC13 · adv M"),mt("Opening wealth restated","Opening wealth বদলে দেওয়া"),same("filed"),same("inc 12 · exm 0.5 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36.5 · prior line5 22"),same("R-C3 meaningful · no flags"),same("Medium"),mt("First verify migration/revised return, then recalculate C1.","আগে migration/revised return verify; তারপর C1 recalc।"),mt("C3 catches the continuity break even when C1 appears zero.","✓ C1 zero হলেও C3 continuity break ধরে।")],
          [same("TC14 · adv N"),mt("Revision after trigger","Trigger-এর পরে revision"),same("filed"),same("inc 12 · exm 0 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36 · prior line5 30"),same("R-C1 strong — note: v1 gap, v2 zero · R-D3 weak"),same("High"),mt("Keep v1 signal open; assess v2 as a separate return version.","v1 signal open; v2 separate version।"),mt("Revision did not close the prior signal; weak timing signal did not create Very High.","✓ Revision old signal বন্ধ করেনি; D3 weak Very High নয়।")],
          [same("TC15 · adv O"),mt("External payroll mismatch plus gap","External payroll mismatch + gap"),same("filed-ext"),same("inc 4.8 · exm 0 · rec 0 · prev 18 · bb 6 · oth 0 · lia 0 · ast 20 · prior line5 18"),same("R-E1 strong · no flags"),same("Very High"),mt("Priority review; verify employer data first.","Priority review; employer data আগে verify।"),mt("External data may be wrong; Very High means priority, not proof.","⚠ External ভুল হতে পারে; Very High priority, proof নয়।")],
          [same("TC16 · adv P"),mt("Registry mismatch only","শুধু registry mismatch"),same("filed-ext"),same("inc 12 · exm 0 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36 · prior line5 30"),same("R-E2 strong · no flags"),same("High"),mt("Detailed review; ownership share and valuation basis.","Detailed review; ownership share ও valuation basis।"),mt("One strong signal does not become Very High automatically.","✓ One strong ≠ Very High।")],
          [same("TC17 · adv Q"),mt("Two external mismatches in same family","দুটি external mismatch — same family"),same("filed-ext"),same("inc 12 · exm 0 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36 · prior line5 30"),same("R-E1 strong + R-E2 strong"),same("High"),mt("Detailed review.","Detailed review।"),mt("Two external signals share a family and do not create Very High.","✓ Same external family → Very High নয়।")],
          [same("TC18 · adv R"),mt("Wrong external match — another TIN","ভুল external match — অন্য TIN"),same("filed-ext"),same("inc 12 · exm 0 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36 · prior line5 30"),same("R-E2 strong"),same("High"),mt("Verification finds wrong TIN → close with no adjustment; increment E2 FP counter.","Wrong TIN → Closed, no adjustment; E2 FP counter বাড়ে।"),mt("Signal is not proof; outcome is a separate event.","✓ Signal ≠ proof; outcome separate event।")],
          [same("TC19 · adv S"),mt("Tax double-counting trap","Tax double-counting ফাঁদ"),same("filed"),same("inc 12 · exm 0 · rec 0 · prev 30 · bb 6 · oth 0 · lia 0 · ast 36 · prior line5 30"),same("No signals · no flags"),same("Low"),mt("No action.","কোনো পদক্ষেপ নয়।"),mt("Tax was not subtracted a second time; otherwise an artificial negative gap would appear.","✓ Tax second time subtract নয়; না হলে artificial negative gap।")],
          [same("TC20 · adv T"),mt("eReturn line-10 plug","eReturn line-10 plug"),same("filed"),same("inc 5 · exm 0 · rec 0 · prev 25 · bb 3 · oth 0 · lia 0 · ast 27 · prior line5 25"),same("No signals · no flags"),same("Low"),mt("Gap is structurally zero; this return teaches nothing about reconciliation.","Gap structurally zero; reconciliation কিছু শেখায় না।"),mt("Structural failure: C1 can never fire if line 10 is not independent.","✗ Structural failure: line10 independent না হলে C1 কখনো fire নয়।")],
          [same("TC21"),same("Asset-driven gap"),same("filed"),same("inc 8 · exm 0 · rec 0 · prev 31 · bb 4.5 · oth 0 · lia 0 · ast 82 · prior line5 31"),same("R-A1 strong + R-B1 meaningful"),same("High"),mt("Detailed review; wealth-source document.","Detailed review; wealth-source document।"),mt("A1/B1 become context so the same gap is not counted twice.","✓ A1/B1 context; gap double count নয়।")],
          [same("TC22"),same("Expenditure-driven gap"),same("filed"),same("inc 6 · exm 0 · rec 0 · prev 25 · bb 14 · oth 0 · lia 0 · ast 26 · prior line5 25"),same("No seed signals · no flags"),same("High"),mt("Ask how expenditure was funded: undeclared loan, gift or income?","খরচের fund source: undeclared loan, gift নাকি income?"),mt("Driver is part of the reason, not a separate rule.","✓ Driver reason-এ, আলাদা rule নয়।")],
        ],
        note: mt(
          "For filed cases the engine may automatically add R-C1 after reconciliation and may move proxy/context rules out of independent counting. The source compares the computed Level with the documented expected Level for every case.",
          "Filed case-এ reconciliation-এর পর engine R-C1 auto-add করতে পারে এবং proxy/context rule independent count থেকে সরাতে পারে। Source প্রতিটি case-এর computed Level documented expected Level-এর সাথে compare করে।"
        ),
      },
      {
        kind: "table",
        title: mt("Self-test coverage — engine behaviour", "Self-test coverage — engine behaviour"),
        columns: [mt("Area","Area"), mt("Assertions executed by the source","Source যে assertion চালায়")],
        rows: [
          [mt("Reconciliation arithmetic","Reconciliation arithmetic"),mt("For every reconciled case: 10−7 equals ΔNW−(Sources−Uses) · every case computed Level equals expected · all combination tests pass.","প্রতিটি reconciled case-এ 10−7 = ΔNW−(Sources−Uses) · সব case computed Level = expected · সব combination PASS।")],
          [same("Data Quality"),mt("Missing component creates no gap · malformed input is not coerced to zero · negative value is INVALID · genuine zero is valid · tax is not subtracted twice · line10=line7 makes gap zero · incomplete coverage is never shown as Low.","Missing component gap নয় · malformed→0 নয় · negative INVALID · genuine 0 valid · tax double subtract নয় · line10=line7 → gap zero · incomplete coverage কখনো Low নয়।")],
          [mt("Risk policy","Risk policy"),mt("Strong alone=High · strong+independent meaningful=Very High · same factKey counted once · strongest same-fact retained and weaker context · different fact+family independent · same family not independent · E1+E2 same-family not Very High · weak alone Low · meaningful alone Medium · no numeric weight · dedup before independence · Control Flags do not create risk · no eligible substantive rule → Undetermined.","Strong একা High · independent meaningful সহ Very High · same factKey একবার · stronger retained, weaker context · different fact+family independent · same family নয় · E1+E2 Very High নয় · weak Low · meaningful Medium · numeric weight নেই · dedup আগে · F flag risk নয় · eligible substantive rule না থাকলে নির্ণয় হয়নি।")],
          [same("Verification"),mt("No Finding before verification · missing/invalid data is not evidence · evidence must name a signal · unknown-signal evidence rejected · verification needs linked evidence · another signal's evidence cannot verify · non-fired signal cannot verify · verifying C1 does not verify E2/D3 · refuting E2 does not refute C1 · original signal/event survives refutation · mixed verification states coexist · Refuted/Pending cannot support Finding · Finding references signal/evidence · sign-off names signal/evidence · generic approval rejected · unrelated evidence rejected · High case cannot close with Pending signal · closure compatibility enforced · Refuted-only may close as no inconsistency · High closure requires second officer · valid conditions allow closure · SLA breach emitted once with case/level/limit/elapsed/actor · event sequence append-only · return versions auditable · verification status does not change Risk Level · evidence checklist is rule-based.","Verification ছাড়া Finding নয় · missing/invalid evidence নয় · evidence signal-linked · unknown signal reject · linked evidence ছাড়া verification নয় · অন্য signal-এর evidence নয় · non-fired signal নয় · C1 verify ≠ E2/D3 verify · E2 refute ≠ C1 refute · original event থাকে · mixed state coexist · Refuted/Pending থেকে Finding নয় · Finding signal/evidence reference · sign-off specific · generic approval reject · unrelated evidence reject · Pending থাকলে High close নয় · closure compatibility · Refuted-only no inconsistency close · second officer required · valid closure · SLA breach once with metadata · append-only sequence · return version auditable · verification Risk Level বদলায় না · checklist rule-based।")],
          [same("UI integrity"),mt("No duplicate DOM id · every rule has fact and evidence family · every A–E rule has an evidence checklist · displayed Risk Level table and code share the same CONFIG source.","Duplicate DOM id নেই · সব rule-এ fact/family · সব A–E rule-এর evidence checklist · displayed Risk Level table ও code একই CONFIG source।")],
          [mt("v7 view-layer integrity","v7 view-layer integrity"),mt("DT0 creates no gap by treating missing as zero · DT0 Level comes only from eligible rules · DT0 coverage limitation remains visible · unavailable charts explain unavailability rather than drawing zero · no history shows trend unavailable · dashboard Risk Level comes from the same engine · no duplicate DOM id.","DT0 missing→0 ধরে gap নয় · DT0 Level eligible rule থেকেই · coverage limitation visible · unavailable chart zero আঁকে না · history নেই→trend unavailable · dashboard Level engine থেকেই · duplicate DOM id নেই।")],
        ],
      },
    ],
  },
];


export const AUDIT_MANUAL_TEST_SUPPLEMENT_BLOCKS: Record<string, ManualBlock[]> = {
  s12: [
    {
      kind: "table" as const,
      title: mt("Individual self-test assertions preserved from the source", "Source-এর প্রতিটি self-test assertion"),
      columns: [same("#"), mt("Area","Area"), mt("Assertion","Assertion")],
      rows: [
        [same("1"),same("Arithmetic"),mt("For every case where reconciliation runs, Gap identity holds: 10 − 7 = ΔNW − (Sources − Uses).","Reconciliation চলা প্রতিটি case-এ Gap identity: 10 − 7 = ΔNW − (Sources − Uses)।")],
        [same("2"),same("Arithmetic"),mt("Every case's computed Level equals the documented expected Level.","প্রতিটি case-এর computed Level নথিভুক্ত প্রত্যাশার সমান।")],
        [same("3"),same("Arithmetic"),mt("All combination tests pass.","Combination test সব PASS।")],
        [same("4"),same("Data Quality"),mt("A missing component creates no gap.","অনুপস্থিত component কোনো gap তৈরি করে না।")],
        [same("5"),same("Data Quality"),mt("Malformed input is not coerced to 0.","Malformed ইনপুট 0 হিসেবে coerce হয় না।")],
        [same("6"),same("Data Quality"),mt("A negative value is detected as INVALID.","ঋণাত্মক মান INVALID হিসেবে ধরা পড়ে।")],
        [same("7"),same("Data Quality"),mt("A genuine zero is valid: 0 ≠ missing.","প্রকৃত শূন্য বৈধ মান: 0 ≠ missing।")],
        [same("8"),same("Data Quality"),mt("Subtracting tax separately would create an artificial gap, so the engine does not do it.","Tax আলাদাভাবে বাদ দিলে কৃত্রিম gap হতো, তাই করা হয়নি।")],
        [same("9"),same("Data Quality"),mt("If line 10 equals line 7, the gap is always zero — independence condition.","Line 10 = line 7 হলে gap সর্বদা শূন্য — independence শর্ত।")],
        [same("10"),same("Data Quality"),mt("Incomplete coverage is never displayed as Low.","অসম্পূর্ণ coverage কখনো Low দেখায় না।")],
        [same("11"),same("Risk policy"),mt("One Strong signal alone = High, not Very High.","Strong একা = High, Very High নয়।")],
        [same("12"),same("Risk policy"),mt("Strong + meaningful from a different family = Very High.","Strong + ভিন্ন family-র meaningful = Very High।")],
        [same("13"),same("Risk policy"),mt("The same factKey is counted once even when rule IDs differ.","একই factKey দুইবার গোনা হয় না, rule ID ভিন্ন হলেও।")],
        [same("14"),same("Risk policy"),mt("Within the same factKey the strongest is retained and the weaker one becomes context.","একই factKey-এ strongest গণনা হয়, weaker context।")],
        [same("15"),same("Risk policy"),mt("Different factKey + different family = independent candidate.","ভিন্ন factKey + ভিন্ন family = স্বাধীন candidate।")],
        [same("16"),same("Risk policy"),mt("Different factKey + same family is not independent.","ভিন্ন factKey + একই family = স্বাধীন নয়।")],
        [same("17"),same("Risk policy"),mt("E1 + E2 from the same family are not independent corroboration.","Same family E1+E2 স্বাধীন corroboration নয়।")],
        [same("18"),same("Risk policy"),mt("One Weak signal alone = Low.","Weak একা = Low।")],
        [same("19"),same("Risk policy"),mt("One Meaningful signal alone = Medium.","Meaningful একা = Medium।")],
        [same("20"),same("Risk policy"),mt("The riskLevel/dedupe functions use no numeric score or weight.","কোনো numeric weight/score ব্যবহার হয়নি।")],
        [same("21"),same("Risk policy"),mt("Deduplication happens before independence assessment.","Deduplication independence-এর আগেই চলে।")],
        [same("22"),same("Risk policy"),mt("A Control Flag does not create substantive Risk Level.","Control Flag substantive Risk Level তৈরি করে না।")],
        [same("23"),same("Risk policy"),mt("When no substantive rule is eligible, Level is Undetermined.","কোনো substantive rule eligible না হলে Level নির্ণয় হয়নি।")],
        [same("24"),same("Verification"),mt("A Finding cannot be created before verification.","Verification ছাড়া Finding হয় না।")],
        [same("25"),same("Verification"),mt("Missing or invalid data is not accepted as evidence.","Missing/invalid data evidence হিসেবে গৃহীত নয়।")],
        [same("26"),same("Verification"),mt("Evidence must be linked to a specific signal.","Evidence নির্দিষ্ট signal-এর সাথে linked হতে হবে।")],
        [same("27"),same("Verification"),mt("Evidence cannot be linked to a signal that did not fire in the case.","Case-এ নেই এমন signal-এ evidence যুক্ত হয় না।")],
        [same("28"),same("Verification"),mt("Verification cannot complete without evidence.","Evidence ছাড়া verification সম্পন্ন হয় না।")],
        [same("29"),same("Verification"),mt("E2 evidence cannot verify C1.","E2-এর evidence দিয়ে C1 verify করা যায় না।")],
        [same("30"),same("Verification"),mt("A signal that did not fire cannot be verified.","Fire করেনি এমন signal verify করা যায় না।")],
        [same("31"),same("Verification"),mt("C1 can be verified using its own evidence.","C1 নিজের evidence দিয়ে verify করা যায়।")],
        [same("32"),same("Verification"),mt("Verifying C1 does not verify E2 or D3.","C1 verify করলে E2/D3 verify হয় না।")],
        [same("33"),same("Verification"),mt("Refuting E2 does not refute C1.","E2 refute করলে C1 refuted হয় না।")],
        [same("34"),same("Verification"),mt("The original signal and case-opening event remain after refutation.","Refutation-এর পরও মূল signal ও opening event অক্ষত।")],
        [same("35"),same("Verification"),mt("Different verification outcomes can coexist in the same case.","একই case-এ ভিন্ন verification outcome পাশাপাশি থাকে।")],
        [same("36"),same("Verification"),mt("A Refuted signal cannot support a Finding.","Refuted signal থেকে Finding হয় না।")],
        [same("37"),same("Verification"),mt("A Pending signal cannot support a Finding.","Pending signal থেকে Finding হয় না।")],
        [same("38"),same("Verification"),mt("A Finding references the specific signal and evidence.","Finding নির্দিষ্ট signal ও evidence reference করে।")],
        [same("39"),same("Verification"),mt("Second-officer sign-off must say which signals and evidence were reviewed.","Sign-off-এ কোন signal/evidence দেখা হয়েছে বলতে হবে।")],
        [same("40"),same("Verification"),mt("Generic 'Reviewed and approved' is rejected.","Generic 'Reviewed and approved' গ্রহণযোগ্য নয়।")],
        [same("41"),same("Verification"),mt("Evidence unrelated to the reviewed signal is rejected in sign-off.","Reviewed signal-এর সাথে unrelated evidence গ্রহণযোগ্য নয়।")],
        [same("42"),same("Verification"),mt("D3 remains Pending when no linked evidence exists.","D3-তে linked evidence না থাকলে verification হয় না।")],
        [same("43"),same("Closure"),mt("A High case cannot close while any signal remains unverified/Pending.","High case-এ সব signal verify না হলে closure নয়।")],
        [same("44"),same("Closure"),mt("Verified is incompatible with 'no inconsistency established'.","Verified → 'কোনো অসঙ্গতি প্রতিষ্ঠিত হয়নি' অসঙ্গত।")],
        [same("45"),same("Closure"),mt("Not verified is incompatible with 'explanation accepted'.","Not verified → 'ব্যাখ্যা গৃহীত' অসঙ্গত।")],
        [same("46"),same("Closure"),mt("If all signals are Refuted, 'no inconsistency established' is allowed.","সব signal Refuted হলে 'কোনো অসঙ্গতি প্রতিষ্ঠিত হয়নি' চলে।")],
        [same("47"),same("Closure"),mt("A High case cannot close without second-officer sign-off.","Second-officer sign-off ছাড়া High case বন্ধ হয় না।")],
        [same("48"),same("Closure"),mt("When every condition is satisfied, closure succeeds with governing status Verified.","সব শর্ত পূরণ হলে governing status Verified সহ case close হয়।")],
        [same("49"),same("SLA"),mt("An SLA breach event is created once per case.","SLA breach event একবারই তৈরি হয়।")],
        [same("50"),same("SLA"),mt("The breach event records case, level, limit, elapsed time and actor.","SLA breach event case, level, limit, elapsed ও actor রাখে।")],
        [same("51"),same("Audit event"),mt("Prototype events have increasing sequence numbers, not timestamps.","Prototype event-এ seq আছে, timestamp নয়।")],
        [same("52"),same("Audit event"),mt("Verification and sign-off events remain append-only.","Verification ও sign-off event append-only থাকে।")],
        [same("53"),same("Versioning"),mt("Return version is independently auditable.","Return version আলাদাভাবে auditable।")],
        [same("54"),same("Risk policy"),mt("Verification status does not change Risk Level.","Verification status Risk Level বদলায় না।")],
        [same("55"),same("Evidence"),mt("Evidence checklist is rule-based.","Evidence checklist rule-ভিত্তিক।")],
        [same("56"),same("UI integrity"),mt("No duplicate DOM IDs exist in the source page.","DOM-এ duplicate id নেই।")],
        [same("57"),same("Rule integrity"),mt("Every rule defines both fact and evidence family.","প্রতিটি rule-এ fact ও evidence family নির্ধারিত।")],
        [same("58"),same("Evidence"),mt("Every A–E rule has an evidence checklist.","প্রতিটি A–E rule-এর evidence checklist আছে।")],
        [same("59"),same("Configuration"),mt("Displayed Risk Level rows and code come from the same CONFIG source.","Risk Level table ও code একই CONFIG source থেকে।")],
        [same("60"),same("v7 view layer"),mt("DT0 creates no gap by treating missing data as zero.","DT0 case-এ missing data-কে zero ধরে gap তৈরি হয় না।")],
        [same("61"),same("v7 view layer"),mt("DT0 Level comes only from eligible rules, never fabricated logic.","DT0 Level eligible rule থেকেই আসে, fabricate নয়।")],
        [same("62"),same("v7 view layer"),mt("DT0 coverage limitation remains visible.","DT0 coverage limitation দৃশ্যমান থাকে।")],
        [same("63"),same("v7 view layer"),mt("Unavailable charts explain unavailability instead of drawing zero.","Unavailable chart zero আঁকে না; কারণ দেখায়।")],
        [same("64"),same("v7 view layer"),mt("Without history, the trend view says unavailable.","History না থাকলে trend unavailable বলে।")],
        [same("65"),same("v7 view layer"),mt("Dashboard Risk Level comes from the same engine.","Dashboard Risk Level engine থেকেই আসে।")],
        [same("66"),same("v7 view layer"),mt("The v7 view also checks for duplicate DOM IDs.","v7 view duplicate DOM id-ও check করে।")],
      ],
      note: mt("Some assertions execute once per applicable test case, so the runtime count can exceed this unique assertion catalogue.","কিছু assertion applicable test case প্রতি একবার চলে; তাই runtime check count এই unique assertion catalogue-এর চেয়ে বেশি হতে পারে।"),
    },
  ],
};
